- name: Install KVM packages
  ansible.builtin.package:
    name: "{{ rhel_based }}"
    state: latest

- name: Ensure services are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - libvirtd

- name: Collect facts about system services
  ansible.builtin.service_facts:
  register: services_state

- name: Get status of KVM 
  ansible.builtin.debug:
    var: "{{ item }}"
  loop: 
    - ansible_facts.services['libvirtd.service'].state
    - ansible_facts.services['libvirt-guests.service'].state

- name: User.yml | Create and add user to KVM groups
  include: user.yml
